name: CI/CD 

on:
  push:
    branches:
      - dev
      - main

jobs:
  build_and_test_on_dev_merge:
    if: github.ref == 'refs/heads/dev'  # Trigger only for dev branch
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js for Frontend
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Frontend Dependencies
      run: |
        cd frontend
        npm install

    - name: Set up Python for Backend
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Backend Dependencies
      run: |
        cd backend
        npm install

    - name: Run Unit Tests for Frontend
      run: |
        cd frontend
        npm run test

    - name: Run Unit Tests for Backend
      run: |
        cd backend
        npm run test

    - name: Create Pull Request to merge dev to main (if tests pass)
      if: success()  # Only run if previous steps were successful
      run: |
        git checkout main
        git merge dev
        git push origin main

  build_and_test_on_main_merge:
    needs: build_and_test_on_dev_merge
    if: github.ref == 'refs/heads/main'  # Trigger only for main branch
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js for Frontend
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Frontend Dependencies
      run: |
        cd frontend
        npm install

    - name: Set up Python for Backend
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Backend Dependencies
      run: |
        cd backend
        npm install

    - name: Run Unit Tests for Frontend
      run: |
        cd frontend
        npm run test

    - name: Run Unit Tests for Backend
      run: |
        cd backend
        npm run test

    - name: Run E2E Tests
      run: |
        cd frontend
        npm run test

    - name: Install Docker Compose
      run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.22.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version # Verify installation

    - name: Build Docker Images
      run: |
        docker-compose up --build -d

    - name: Push Docker Images to Docker Hub
      run: |
        docker login -u marliyatou -p ${{ secrets.DOCKER_TOKEN }}
        docker-compose -f docker-compose.yml push
